### ISSUE TITLE
Shortcut to comment code 

### ISSUE THREAD

**Issue by saurabh-ku** [fredoverflow/freditor#2]
Hello, 

I found about about Clopad while I was following your Advent of Code 2020 series. I immediately started using Clopad and think it is an amazing editor to just get in and start working with Clojure code.

One of the things I instinctively tried to do was to use the short cut `Ctrl + /` (On Windows) comment a selection of code, but it seems this feature is not present it. 

I would love to have this feature in Clopad and would love to contribute this feature to your repo.

From my initial analysis I can see that the key press events are being handled here
https://github.com/fredoverflow/freditor/blob/f5cc18b650131154daaf84d57500000a5c42e9b7/src/main/java/freditor/FreditorUI.java#L126

And adding this feature would require to first listen to the shortcut and then use the editors API to add `;` at the start of all the lines selected.

**Comment by fredoverflow** [comment]
The idiomatic way to comment a multi-line form is to prepend it with `#_` instead of commenting multiple lines individually: `#_(f x y z ...)`

https://clojure.org/reference/reader#_dispatch
